In [1]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: ignored

In [ ]:
%cd drive/MyDrive

/content/drive/MyDrive

In [ ]:
%cd explore_cds/

/content/drive/My Drive/explore_cds

In [ ]:
import pandas as pd
cds_data = pd.read_csv("cds.csv")

In [ ]:
cds_data.iloc[:,12] = cds_data.iloc[:,12].pct_change()

In [ ]:
cds_data

               Date Ticker  ...       PX9      PX10
0        2015-01-01      A  ...  158.6000       NaN
1        2015-01-02      A  ...  158.7750  0.001070
2        2015-01-05      A  ...  157.3850 -0.009206
3        2015-01-06      A  ...  165.6550  0.054308
4        2015-01-07      A  ...  166.2150  0.002331
...             ...    ...  ...       ...       ...
1061162  2021-09-06  ZIGGO  ...  345.8258  0.003031
1061163  2021-09-07  ZIGGO  ...  358.9416  0.036968
1061164  2021-09-08  ZIGGO  ...  358.5867 -0.001271
1061165  2021-09-09  ZIGGO  ...  356.5323 -0.005362
1061166  2021-09-10  ZIGGO  ...  357.0261  0.001153

[1061167 rows x 13 columns]

In [ ]:
cds_data = cds_data[cds_data["Date"]!="2015-01-01"]

In [ ]:
preprocessed = cds_data.iloc[:,[0,1,2,12]]

In [ ]:
news_data = pd.read_csv("analyst_ratings_processed.csv")

In [ ]:
#news_data["date"] = pd.to_datetime(news_data["date"]).dt.strftime('%Y-%m-%d')
news_data["date"] = news_data["date"].astype(str).map(lambda date_string: date_string[0:10])
new_df = pd.merge(preprocessed, news_data, left_on=['Date','Ticker'], right_on = ['date','stock'])
new_df = new_df[["title","date","PX10","stock","Company"]]

In [ ]:
new_df

                                                    title  ...                   Company
0            Agilent Introduces GenetiSure Pre-Screen Kit  ...  Agilent Technologies Inc
1       S&P 500 Stocks With Most Active Options Today:...  ...  Agilent Technologies Inc
2       Simons-Founded Renaissance Technologies Buys A...  ...  Agilent Technologies Inc
3       Agilent's Dako, ONO PHARMACEUTICAL, Announce P...  ...  Agilent Technologies Inc
4       Agilent Sees FY15 Adj. EPS $1.67-$1.73 vs $1.7...  ...  Agilent Technologies Inc
...                                                   ...  ...                       ...
114196                Afternoon Market Stats in 5 Minutes  ...          Exxon Mobil Corp
114197                  Morning Market Stats in 5 Minutes  ...          Exxon Mobil Corp
114198  Shares of several energy companies are trading...  ...          Exxon Mobil Corp
114199                  Morning Market Stats in 5 Minutes  ...          Exxon Mobil Corp
114200  Shares of several energy companies are trading...  ...          Exxon Mobil Corp

[114201 rows x 5 columns]

In [ ]:
new_df['date'] = pd.to_datetime(new_df['date'])
new_df = new_df.sort_values(by='date')
new_df.dtypes

title              object
date       datetime64[ns]
PX10              float64
stock              object
Company            object
dtype: object

In [ ]:
new_df

                                                    title  ...                              Company
35833     A Few Ways To Play A Stronger US Housing Market  ...                        DR Horton Inc
65442   #Premarket Prep Technical Update - Eli Lilly T...  ...                       Eli Lilly & Co
91108   Could A Ban On Microbeads Overhaul The Cosmeti...  ...              Procter   Gamble Co The
35413                        Stocks Hitting 52-Week Highs  ...                Quest Diagnostics Inc
65064   Raymond James Upgrades Laboratory of America t...  ...  Laboratory Corp of America Holdings
...                                                   ...  ...                                  ...
42616   Morgan Stanley Maintains Overweight on Ford Mo...  ...                        Ford Motor Co
64404   Shares of several financial service companies ...  ...                           Loews Corp
84705   Shares of several industrials companies are tr...  ...                Norfolk Southern Corp
94319   Shares of several financial service companies ...  ...                           Prudential
114200  Shares of several energy companies are trading...  ...                     Exxon Mobil Corp

[114201 rows x 5 columns]

In [ ]:
train_df = new_df[new_df['date']<="2019-05-31"]
val_df = new_df[(new_df['date']>="2019-06-01") & (new_df['date']<"2020-03-31")]
test_df = new_df[new_df['date']>="2020-04-01"]

In [ ]:
train_df.to_csv("train.csv")
val_df.to_csv("validation.csv")
test_df.to_csv("test.csv")

In [ ]:
new_df.to_csv("cds_with_news.csv")

In [ ]:
preprocessed.to_csv("Preprocessed.csv")

In [ ]:
from datetime import timezone
import datetime
start_dt = datetime.datetime(2021, 1, 1)
unix_start_dt = start_dt.replace(tzinfo=timezone.utc).timestamp()
print(unix_start_dt)
end_dt = datetime.datetime(2021, 10, 16)
unix_end_dt = end_dt.replace(tzinfo=timezone.utc).timestamp()
print(unix_end_dt)

1609459200.0
1634342400.0

In [ ]:
import glob
my_df = pd.read_csv("../finhub_news/AAPL.csv")
my_df["date"] = pd.to_datetime(my_df["datetime"], unit='s').dt.strftime('%Y-%m-%d')
queried = preprocessed[preprocessed['Ticker']=="AAPL"];
new_df = pd.merge(my_df, queried, left_on='date', right_on = 'Date')
new_df[["headline","summary","PX10","date"]]

                                               headline  ...        date
0     Dow Jones Futures: Market Rally Retreats Amid ...  ...  2021-09-10
1     The S&P 500 Has Had a Good Run. Why Wall Stree...  ...  2021-09-10
2     Wall Street ends down, Apple sinks on app stor...  ...  2021-09-10
3     U.S. lawmakers say decision in Apple/Epic figh...  ...  2021-09-10
4                         Why Apple Stock Dropped Today  ...  2021-09-10
...                                                 ...  ...         ...
8216  Samsung Picks Early Launch For Flagship Galaxy...  ...  2021-01-04
8217     Apple’s Updated Mac Screen Will Arrive In 2021  ...  2021-01-04
8218  Healthcare Report Card: Companies That Failed ...  ...  2021-01-04
8219  New Apple Leak Reveals Powerful MacBook Pro Up...  ...  2021-01-04
8220               Three Apple battles to watch in 2021  ...  2021-01-04

[8221 rows x 4 columns]

In [ ]:
import glob
path = "../finhub_news/*"
for file in glob.glob(path):
    symbol = file[15:-4]
    news_df = pd.read_csv(file)
    news_df["date"] = pd.to_datetime(news_df["datetime"], unit='s').dt.strftime('%Y-%m-%d')
    queried = preprocessed[preprocessed['Ticker']==symbol];
    new_df = pd.merge(news_df, queried, left_on='date', right_on = 'Date')
    new_df = new_df[["headline","summary","PX10","date"]]
    new_df.to_csv(f"../cds_with_news/{symbol}.csv")
    #csv_file = pd.read_csv(file)
    #print(csv_file)

In [ ]:
preprocessed = pd.read_csv("Preprocessed.csv")

In [ ]:
preprocessed = preprocessed[preprocessed["Date"]!="2015-01-01"]

         Unnamed: 0        Date Ticker                   Company      PX10
1                 1  2015-01-02      A  Agilent Technologies Inc  0.001070
2                 2  2015-01-05      A  Agilent Technologies Inc -0.009206
3                 3  2015-01-06      A  Agilent Technologies Inc  0.054308
4                 4  2015-01-07      A  Agilent Technologies Inc  0.002331
5                 5  2015-01-08      A  Agilent Technologies Inc -0.017130
...             ...         ...    ...                       ...       ...
1061162     1061162  2021-09-06  ZIGGO                     Ziggo  0.003031
1061163     1061163  2021-09-07  ZIGGO                     Ziggo  0.036968
1061164     1061164  2021-09-08  ZIGGO                     Ziggo -0.001271
1061165     1061165  2021-09-09  ZIGGO                     Ziggo -0.005362
1061166     1061166  2021-09-10  ZIGGO                     Ziggo  0.001153

[1060598 rows x 5 columns]

In [ ]:
!pip install motor
!pip install pymongo[srv]
!pip install DateTime
!pip install dnspython

Requirement already satisfied: motor in /usr/local/lib/python3.7/dist-packages (2.5.1)
Requirement already satisfied: pymongo<4,>=3.12 in /usr/local/lib/python3.7/dist-packages (from motor) (3.12.1)
Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.7/dist-packages (3.12.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from pymongo[srv]) (2.1.0)
Requirement already satisfied: DateTime in /usr/local/lib/python3.7/dist-packages (4.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from DateTime) (2018.9)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.7/dist-packages (from DateTime) (5.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from zope.interface->DateTime) (57.4.0)
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (2.1.0)

In [ ]:
import pymongo
 
client = pymongo.MongoClient("mongodb+srv://analytics:71mpmU8Lw5ngKhe6@cluster0.lln5s.mongodb.net/")

database = client['portfolio_alert']
counterparty_collection = database.get_collection('counterparty')
news_collection = database.get_collection('news')

In [ ]:
from datetime import timezone
import datetime
start_dt = datetime.datetime(2021, 1, 1)
unix_start_dt = start_dt.replace(tzinfo=timezone.utc).timestamp()
print(unix_start_dt)
end_dt = datetime.datetime(2021, 10, 16)
unix_end_dt = end_dt.replace(tzinfo=timezone.utc).timestamp()
print(unix_end_dt)

1609459200.0
1634342400.0

In [ ]:
data_list = list(news_collection.find({"datetime":{"$gte":unix_start_dt,"$lt":unix_end_dt}, "counterparty": "AAPL"}))

In [ ]:
finnhub_data = pd.DataFrame(data_list)

In [ ]:
new_df = pd.merge(preprocessed,finnhub_data,  how='left', left_on=['Date','Ticker'], right_on = ['date','counterparty'])

In [ ]:
AAPL = new_df[new_df["Ticker"]=="AAPL"]

In [ ]:
AAPL_filtered = AAPL.loc[:,["Date","Ticker","PX10","headline","summary",]]